backend:
  name: git-gateway
  repo: skiglock/atoll
  branch: main
local_backend: true
locale: 'ru'

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
# --------------------Основные страницы---------------------------
  - name: 'main_pages'
    label: 'Основные страницы'
    create: false
    files:
      - label: 'Главная'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'ID', name: 'id', widget: 'id' }
          - { label: 'Заголовок страницы', name: 'title', widget: 'string' }
          - {
              label: 'Мета-тэг описания',
              name: 'description',
              widget: 'string'
            }
      - label: 'О команде'
        name: 'about'
        file: 'content/about.md'
        fields:
          - { label: 'ID', name: 'id', widget: 'id' }
          - { label: 'Заголовок страницы', name: 'title', widget: 'string' }
          - {
              label: 'Мета-тэг описания',
              name: 'description',
              widget: 'string'
            }
      - label: 'Блог'
        name: 'blog'
        file: 'content/blog.md'
        fields:
          - { label: 'ID', name: 'id', widget: 'id' }
          - { label: 'Заголовок страницы', name: 'title', widget: 'string' }
          - {
              label: 'Мета-тэг описания',
              name: 'description',
              widget: 'string'
            }
      - label: 'Контакты'
        name: 'contacts'
        file: 'content/contacts.md'
        fields:
          - { label: 'ID', name: 'id', widget: 'id' }
          - { label: 'Заголовок страницы', name: 'title', widget: 'string' }
          - {
              label: 'Мета-тэг описания',
              name: 'description',
              widget: 'string'
            }
      - label: 'Кейсы'
        name: 'cases'
        file: 'content/cases.md'
        fields:
          - { label: 'ID', name: 'id', widget: 'id' }
          - { label: 'Заголовок страницы', name: 'title', widget: 'string' }
          - {
              label: 'Мета-тэг описания',
              name: 'description',
              widget: 'string'
            }


  # --------------------Динамические страницы---------------------------
  - name: 'pages'
    label: 'Допольнительные страницы'
    folder: 'content/pages'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'ID', name: 'id', widget: 'id' }
      - { label: 'Заголовок страницы', name: 'title', widget: 'string' }
      - { label: 'Мета-тэг описания', name: 'description', widget: 'string' }

  # --------------------Блог---------------------------
  - name: 'blog'
    label: 'Блог'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'ID', name: 'id', widget: 'id' }
      - { label: 'Заголовок поста', name: 'title', widget: 'string' }
      - { label: 'Мета-тэг описания', name: 'description', widget: 'string' }
      - { label: 'Дата', name: 'date', picker_utc: false, widget: 'datetime' }
      - {
          label: 'Опубликовано',
          name: 'published',
          widget: 'boolean',
          default: false
        }
      - { label: 'Главная картинка', name: 'img', widget: 'image', default: '' }
      - { label: 'Текст краткого описания', name: 'desc', widget: 'markdown' }
      - { label: 'Текст полного описания', name: 'full', widget: 'markdown' }   