backend:
  name: git-gateway
  repo: skiglock/atoll
  branch: main
local_backend: true
locale: 'ru'

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  # --------------------Основные страницы---------------------------
  - name: 'main_pages'
    label: 'Основные страницы'
    create: false
    files:
      - label: 'Главная'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'ID', name: 'id', widget: 'id' }
          - { label: 'Заголовок страницы', name: 'title', widget: 'string' }
          - {
              label: 'Мета-тэг описания',
              name: 'description',
              widget: 'string'
            }
      - label: 'О команде'
        name: 'about'
        file: 'content/about.md'
        fields:
          - { label: 'ID', name: 'id', widget: 'id' }
          - { label: 'Заголовок страницы', name: 'title', widget: 'string' }
          - {
              label: 'Мета-тэг описания',
              name: 'description',
              widget: 'string'
            }
      - label: 'Блог'
        name: 'blog'
        file: 'content/blog.md'
        fields:
          - { label: 'ID', name: 'id', widget: 'id' }
          - { label: 'Заголовок страницы', name: 'title', widget: 'string' }
          - {
              label: 'Мета-тэг описания',
              name: 'description',
              widget: 'string'
            }
      - label: 'Контакты'
        name: 'contacts'
        file: 'content/contacts.md'
        fields:
          - { label: 'ID', name: 'id', widget: 'id' }
          - { label: 'Заголовок страницы', name: 'title', widget: 'string' }
          - {
              label: 'Мета-тэг описания',
              name: 'description',
              widget: 'string'
            }
      - label: 'Кейсы'
        name: 'cases'
        file: 'content/cases.md'
        fields:
          - { label: 'ID', name: 'id', widget: 'id' }
          - { label: 'Заголовок страницы', name: 'title', widget: 'string' }
          - {
              label: 'Мета-тэг описания',
              name: 'description',
              widget: 'string'
            }

  # --------------------Динамические страницы---------------------------
  - name: 'pages'
    label: 'Допольнительные страницы'
    folder: 'content/pages'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'ID', name: 'id', widget: 'id' }
      - { label: 'Заголовок страницы', name: 'title', widget: 'string' }
      - { label: 'Мета-тэг описания', name: 'description', widget: 'string' }
      - label: 'Компоненты страницы'
        name: 'layout'
        widget: 'list'
        types:
          # SectionHead
          - label: 'Секция с заголовком и описанием 1'
            name: 'head'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'head'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionHeadTwo
          - label: 'Секция с заголовком и описанием 2'
            name: 'head-two'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'head-two'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionHeadThree
          - label: 'Секция с заголовком и описанием 3'
            name: 'head-three'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'head-three'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionOther
          - label: 'Секция с историей'
            name: 'other'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'other'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionConsultation
          - label: 'Секция с консультацией'
            name: 'consultation'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'consultation'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionMessage
          - label: 'Секция заголовок с кнопкой'
            name: 'message'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'message'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionQuote
          - label: 'Секция с цитатой'
            name: 'quote'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'quote'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionContacts
          - label: 'Секция с контактами'
            name: 'contacts'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'contacts'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionOrder
          - label: 'Секция с формой'
            name: 'order'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'order'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionTarget
          - label: 'Секция с общей фоткой и текстом'
            name: 'target'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'target'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionTeam
          - label: 'Секция с командой'
            name: 'team'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'team'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionResults
          - label: 'Секция результаты'
            name: 'results'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'results'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionCards
          - label: 'Секция с карточками'
            name: 'cards'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'cards'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionPrice
          - label: 'Секция цена'
            name: 'price'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'price'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionFaq
          - label: 'Секция вопросы/ответы'
            name: 'faq'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'faq'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionClients
          - label: 'Секция клиенты'
            name: 'clients'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'clients'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

          # SectionPlans
          - label: 'Секция планы'
            name: 'plans'
            widget: object,
            fields:
              - {
                  label: 'name',
                  name: 'name',
                  widget: 'hidden',
                  default: 'plans'
                }
              - { label: 'ID', name: 'id', widget: 'id' }
              - { label: 'Заголовок', name: 'title', widget: string }

  # --------------------Блог---------------------------
  - name: 'blog'
    label: 'Блог'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'ID', name: 'id', widget: 'id' }
      - { label: 'Заголовок поста', name: 'title', widget: 'string' }
      - { label: 'Мета-тэг описания', name: 'description', widget: 'string' }
      - { label: 'Дата', name: 'date', picker_utc: false, widget: 'datetime' }
      - {
          label: 'Опубликовано',
          name: 'published',
          widget: 'boolean',
          default: false
        }
      - { label: 'Главная картинка', name: 'img', widget: 'image' }
      - { label: 'Текст краткого описания', name: 'desc', widget: 'markdown' }
      - { label: 'Текст полного описания', name: 'full', widget: 'markdown' }

  # --------------------Кейсы---------------------------
  - name: 'cases'
    label: 'Кейсы'
    folder: 'content/cases'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'ID', name: 'id', widget: 'id' }
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Мета-тэг описания', name: 'description', widget: 'string' }
      - { label: 'Дата', name: 'date', picker_utc: false, widget: 'datetime' }
      - {
          label: 'Опубликовано',
          name: 'published',
          widget: 'boolean',
          default: false
        }
      - { label: 'Категория', name: 'category', widget: 'string' }
      - { label: 'Картинка', name: 'img', widget: 'image' }
      - { label: 'Логотип', name: 'logo', widget: 'image' }
      - { label: 'Краткое описание', name: 'desc', widget: markdown }
      - { label: 'О компании', name: 'about', widget: 'markdown' }
      - { label: 'История', name: 'history', widget: 'markdown' }
      - { label: 'Что мы сделали?', name: 'made', widget: 'markdown' }
      - { label: 'Результат', name: 'result', widget: 'markdown' }
